# Generated by Django 2.2.6 on 2019-10-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterMgmt', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='img_or_vid',
            field=models.FileField(upload_to='', verbose_name='Image or Video about the resource'),
        ),
    ]
