# Generated by Django 2.2.6 on 2019-10-22 10:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('waterMgmt', '0008_auto_20191022_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 10, 32, 16, 994190, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='resource',
            name='img_or_vid',
            field=models.FileField(blank=True, help_text='Image or Video representing the problem/solution.', null=True, upload_to='img_vid/', verbose_name='Image or Video'),
        ),
    ]
