# Generated by Django 2.2.6 on 2019-10-22 10:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('waterMgmt', '0009_auto_20191022_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 10, 47, 38, 974352, tzinfo=utc)),
        ),
    ]
