# Generated by Django 2.2.6 on 2019-10-22 11:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('waterMgmt', '0012_auto_20191022_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text="User's Profile Picture", null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 11, 56, 22, 892233, tzinfo=utc)),
        ),
    ]
